#!/usr/bin/env python3
import numpy as np
import sys
import argparse
import tensorflow as tf
from second_order import second_order
from single_pendulum_v2 import pendulum
from linear_control import PIDcontroller
import os
import pickle
import shelve
from tensorflow import keras
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit

parser = argparse.ArgumentParser(\
        prog='Test the performance of neural network',\
        description='Environment where the trained neural network is tested'
        )


parser.add_argument('-loc', default='./train_data/', help='location to store responses, default: ./train_data')
parser.add_argument('-init', default=0, help='offset from working point')
parser.add_argument('-wp', default=0, help='working point')
parser.add_argument('-model_path', default='./nn_mdl', help='path to neural network model')


args = parser.parse_args()

model_path = vars(args)['model_path']

dir = vars(args)['loc']

# Working point
wp = float(vars(args)['wp'])
# initial conditions of pendulum
theta = wp + float(vars(args)['init'])




print('----------------------------------------------------------------')
print('Fetching training info from: ', str(dir+'/readme'))
print('----------------------------------------------------------------')
with shelve.open( str(dir+'/readme')) as db:
    zeta=float((db)['zeta'])
    wn=float((db)['wn'])
    sim_time = int((db)['t'])
    dt = float((db)['dt'])

db.close()


print('----------------------------------------------------------------')
print('Training Information: ')
print('----------------------------------------------------------------')
with shelve.open(str(dir+'/readme')) as db:
    for key,value in db.items():
        print("{}: {}".format(key, value))
db.close()
print('wp: ',wp)
print('theta: ', theta)
print('----------------------------------------------------------------')



print('------------------------------------------------------------------------------------------------------')
print('Fetching neural network model from: ', str(model_path ))
print('------------------------------------------------------------------------------------------------------')

nn_model = keras.models.load_model(str(model_path))

inputsize = nn_model.get_input_shape_at(0)

# input to neural network
N=200
nn_input_matrix = np.zeros((1,N))

# Conversion to radians
deg2rad = np.pi/180

wp = wp*deg2rad
theta = 0*deg2rad


# constant
t = 0


error = 0
ref =   40.107 * deg2rad

if __name__ == '__main__':


    # Size for arrays
    total_steps = int(np.ceil(t/dt))
    # from other branch, will need to be change
    dt = 0.01
    total_steps = 2500
    # sim_time = t
    #

    t = 0
    # counter
    step = 0

    # Creat Input

    # fake_control = generateCombinationInput(total_steps,50,-0.5,0.5)

    # y generated by nonlinear model
    y_hat = np.zeros(total_steps)

    bias_true = np.zeros(total_steps)
    bias_pred = np.zeros(total_steps)


    # Error between y_hat and y_star
    e = np.zeros(total_steps)

    # control received by nonlinear model
    u_hat = np.zeros(total_steps)

    # Generated neural network control output
    y_nn = np.zeros(total_steps)

    # Error between reference and y_hat
    error = np.zeros(total_steps)

    # Nonlinear model of the pendulum
    pendulums = pendulum(wn=wn,zeta=zeta,time_step=dt,y=theta)
    # pendulums = second_order(wn=wn,zeta=zeta,time_step=dt,y=theta,y_wp=wp)

    # Linear PID Controller
    P=5
    I=2
    D=0
    linear_controller = PIDcontroller(P,I,D,dt=dt)

    sim_time = 25
    bias = 0.5

    while t < sim_time-dt/2:

        # output of nonlinear model
        y_hat[step] = pendulums.getAllStates()[3]
        # output of the linear model


        # Define the initial error
        error[step] = ref - y_hat[step]
        linear_controller.step(error[step])
        control_output = linear_controller.outputControl()

        # linear controller output
        u_hat[step] = control_output

        # Determine where the linear controller will take the linearised model


        nn_input_matrix = np.roll(nn_input_matrix,1) # move elements one timestep back

        # insert new timestep
        nn_input_matrix[0,0] = u_hat[step]/7.04208947208605
        nn_input_matrix[0,100] = np.sin(y_hat[step])

        # reshape
        # print(nn_input_matrix)
        nn_input = nn_input_matrix[0].reshape((1,200))

        nn_output = nn_model.predict(nn_input)
        # print(nn_output)


        y_nn[step] = nn_output[0,0]
        bias_pred[step] = nn_output[0,1]

        bias_true[step] = bias


        pendulums.update_input(u_hat[step])
        pendulums.step()


        # Increment time
        t += dt
        # Increment counter
        step += 1



plt.rc('text', usetex=True)
plt.rc('font', family='serif')
plt.rc('font', size=12)

plt.figure(1)
plt.plot(y_nn,'-', mew=1, ms=8,mec='w')
plt.plot(y_hat,'-', mew=1, ms=8,mec='w')
plt.grid()
plt.legend(['$y_{NN}$','$\hat y$'])

plt.figure(2)
plt.plot(bias_pred,'-', mew=1, ms=8,mec='w')
plt.plot(bias_true,'-', mew=1, ms=8,mec='w')
plt.grid()
plt.legend(['bias pred','bias true'])


plt.figure(3)
plt.plot(u_hat,'-', mew=1, ms=8,mec='w')
plt.grid()
plt.legend(['$\hat u$'])



plt.show()
